### ISSUE TITLE
how to solve the problem that "AssertionError: all the elements in the tensor are zero.: True"

### ISSUE THREAD

**Issue by jiajunsun68** [RocktimJyotiDas/GBLM-Pruner#2]
thanks for ur project.
when i run GBLM-Pruner/gradient_computation.py, I meet a error whose details are below.

Traceback (most recent call last):
  File "GBLM-Pruner/gradient_computation.py", line 206, in <module>
    grad_up.update_gradient(model, nsample)
  File "GBLM-Pruner/gradient_computation.py", line 157, in update_gradient
    assert int(all_zero) == 0, f"all the elements in the tensor are zero.: {all_zero}"
AssertionError: all the elements in the tensor are zero.: True

seems that some tensors are zero. I have no idea about this error. would u please tell me how to solve this?

**Comment by jiajunsun68** [comment]
I don't know why all the elements in subset[name] should be zero or should not be zero.
